# Generated by Django 4.2 on 2023-05-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('kategoria_azon', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=25, unique=True, verbose_name='Kategória neve')),
            ],
        ),
        migrations.CreateModel(
            name='Edesseg',
            fields=[
                ('edesseg_azon', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nev', models.CharField(max_length=60, verbose_name='Édesség neve')),
                ('leiras', models.TextField(verbose_name='Leírás')),
                ('ar', models.IntegerField(verbose_name='Ár (Ft)')),
                ('kep_utvonal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kép elérési útvonala')),
                ('kategoria_azon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategoria', verbose_name='Kategória')),
            ],
        ),
    ]
