# Generated by Django 4.2 on 2023-05-30 15:18

from django.db import migrations

def feltoltes(apps, schema_editor):
    Kategoria = apps.get_model('app', 'Kategoria')
    kategoriak = ['Torta', 'Fagylalt', 'Sütemény']

    for i in range(len(kategoriak)):
        k = Kategoria(i + 1, kategoriak[i])
        k.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(feltoltes)
    ]
